CREATE ROLE PG_USER_NAME WITH LOGIN PASSWORD 'PG_USER_PASSWORD';

CREATE DATABASE PG_DATABASE WITH OWNER PG_USER_NAME TEMPLATE template0 ENCODING PG_DATABASE_ENCODING;

CREATE ROLE PG_REPL_USER_NAME WITH LOGIN REPLICATION PASSWORD 'PG_REPL_USER_PASSWORD';

SELECT pg_create_physical_replication_slot('PG_REPL_USER_NAME', true, false);

\c PG_DATABASE
CREATE EXTENSION pg_stat_statements;